var commentsArray = [
    {
      "id": 1,
      "parent": null,
      "created": "2019-06-22",
      "modified": "2019-06-22",
      "content": "Im so jealous, because Sevilla is my favorite city on this planet, and its 4 years i havent been there. ( my mother is from San Sebastian, my grand-mother went to live near Barcelona, but i love Sevilla so much that i dont have enough time to visit every place. And i was born in Paris, which is totally different )",
      "pings": [],
      "creator": 2,
      "fullname": "Jame Jack",
      "profile_picture_url": "images/m-user-pink.png",
      "created_by_admin": false,
      "created_by_current_user": false,
      "upvote_count": 242,
      "user_has_upvoted": false,
      "downvote_count": 0,
      "user_has_downvoted": false,
      "is_new": false
   },{
      "id": 2,
      "parent": 1,
      "created": "2019-06-23",
      "modified": "2019-06-23",
      "content": "well, very few people in VN listen to indie songs and the music industry is overwhelmed with pop and EDM and all that also, few people in VN listen to rock",
      "creator": 3,
      "fullname": "John Cold",
      "profile_picture_url": "images/m-user-green.png",
      "created_by_admin": false,
      "created_by_current_user": false,
      "upvote_count": 0,
      "user_has_upvoted": false,
      "downvote_count": 0,
      "user_has_downvoted": false,
      "is_new": false
   },{
      "id": 3,
      "parent": 1,
      "created": "2019-06-22",
      "modified": "2019-06-22",
      "content": "When I saw the bags vanish and an age spot fade, I immediately bought a spare!",
      "creator": 4,
      "fullname": "Todd Brown",
      "profile_picture_url": "images/m-user-pink.png",
      "created_by_admin": false,
      "created_by_current_user": false,
      "upvote_count": 0,
      "user_has_upvoted": false,
      "downvote_count": 0,
      "user_has_downvoted": false,
      "is_new": false
   }
   ,{
      "id": 4,
      "parent": null,
      "created": "2019-06-28",
      "modified": "2019-06-28",
      "content": "Great, non irritating eye cream. Better tan dermatologist product costing 10x more! Absorbs easy and leaves area soft to the touch. Need very little so should last a long time. When I saw the bags vanish and an age spot fade, I immediately bought a spare!",
      "pings": [],
      "creator": 1,
      "fullname": "John",
      "profile_picture_url": "images/m-trithong.png",
      "created_by_admin": false,
      "created_by_current_user": false,
      "upvote_count": 0,
      "user_has_upvoted": false,
      "downvote_count": 0,
      "user_has_downvoted": false,
      "is_new": false
   }
   ,{
      "id": 5,
      "parent": null,
      "created": "2019-06-30",
      "modified": "2019-06-30",
      "content": "Great, non irritating eye cream. Better tan dermatologist product costing 10x more! Absorbs easy and leaves area soft to the touch. Need very little so should last a long time. When I saw the bags vanish and an age spot fade, I immediately bought a spare!",
      "pings": [],
      "creator": 1,
      "fullname": "Peter",
      "profile_picture_url": "images/m-trithong.png",
      "created_by_admin": false,
      "created_by_current_user": false,
      "upvote_count": 0,
      "user_has_upvoted": false,
      "downvote_count": 0,
      "user_has_downvoted": false,
      "is_new": false
   }

]
    